version: '3'

services:
  postgresql:
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "127.0.0.1:5432:5432"
